In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits
data=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.33, random_state=42)

In [6]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

from sklearn.svm import SVC
svm=SVC()

In [7]:
lg.fit(X_train,y_train)
lg.score(X_test,y_test)

C:\Users\Amar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [8]:
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9730639730639731

In [9]:
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9865319865319865

In [10]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

### EX. KFold

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [13]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9865319865319865

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(LogisticRegression(),data.data,data.target)

C:\Users\Amar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Amar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [16]:
cross_val_score(SVC(),data.data,data.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=10),data.data,data.target)

array([0.89722222, 0.84166667, 0.9275766 , 0.93871866, 0.89693593])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=15),data.data,data.target)

array([0.925     , 0.86388889, 0.93314763, 0.95264624, 0.90529248])